/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AbstractScoreVault } from "./AbstractScoreVault";
export type { ScoreVault } from "./ScoreVault";
