/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "CoreVoting",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.CoreVoting__factory>;
    getContractFactory(
      name: "Airdrop",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.Airdrop__factory>;
    getContractFactory(
      name: "OptimisticGrants",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.OptimisticGrants__factory>;
    getContractFactory(
      name: "Spender",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.Spender__factory>;
    getContractFactory(
      name: "Timelock",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.Timelock__factory>;
    getContractFactory(
      name: "Treasury",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.Treasury__factory>;
    getContractFactory(
      name: "ICoreVoting",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.ICoreVoting__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "ILockingVault",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.ILockingVault__factory>;
    getContractFactory(
      name: "IVotingVault",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.IVotingVault__factory>;
    getContractFactory(
      name: "Authorizable",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.Authorizable__factory>;
    getContractFactory(
      name: "ERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.ERC20Permit__factory>;
    getContractFactory(
      name: "ERC20PermitWithMint",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.ERC20PermitWithMint__factory>;
    getContractFactory(
      name: "AbstractMerkleRewards",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.AbstractMerkleRewards__factory>;
    getContractFactory(
      name: "MerkleRewards",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.MerkleRewards__factory>;
    getContractFactory(
      name: "Storage",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.Storage__factory>;
    getContractFactory(
      name: "MockCoreVoting",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.MockCoreVoting__factory>;
    getContractFactory(
      name: "MockDoubleSpender",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.MockDoubleSpender__factory>;
    getContractFactory(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.MockERC20__factory>;
    getContractFactory(
      name: "MockHistoryTracker",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.MockHistoryTracker__factory>;
    getContractFactory(
      name: "MockLockingVault",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.MockLockingVault__factory>;
    getContractFactory(
      name: "MockTokenLogic",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.MockTokenLogic__factory>;
    getContractFactory(
      name: "MockVotingVault",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.MockVotingVault__factory>;
    getContractFactory(
      name: "Reverter",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.Reverter__factory>;
    getContractFactory(
      name: "ReadAndWriteAnyStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.ReadAndWriteAnyStorage__factory>;
    getContractFactory(
      name: "TestCoreVoting",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.TestCoreVoting__factory>;
    getContractFactory(
      name: "TestTreasury",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.TestTreasury__factory>;
    getContractFactory(
      name: "TestVestingVault",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.TestVestingVault__factory>;
    getContractFactory(
      name: "SimpleProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.SimpleProxy__factory>;
    getContractFactory(
      name: "FrozenLockingVault",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.FrozenLockingVault__factory>;
    getContractFactory(
      name: "FrozenVestingVault",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.FrozenVestingVault__factory>;
    getContractFactory(
      name: "GSCVault",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.GSCVault__factory>;
    getContractFactory(
      name: "AbstractLockingVault",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.AbstractLockingVault__factory>;
    getContractFactory(
      name: "LockingVault",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.LockingVault__factory>;
    getContractFactory(
      name: "NonVotingVault",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.NonVotingVault__factory>;
    getContractFactory(
      name: "OptimisticRewards",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.OptimisticRewards__factory>;
    getContractFactory(
      name: "AbstractVestingVault",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.AbstractVestingVault__factory>;
    getContractFactory(
      name: "VestingVault",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.VestingVault__factory>;

    getContractAt(
      name: "IERC20Permit",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "CoreVoting",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.CoreVoting>;
    getContractAt(
      name: "Airdrop",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.Airdrop>;
    getContractAt(
      name: "OptimisticGrants",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.OptimisticGrants>;
    getContractAt(
      name: "Spender",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.Spender>;
    getContractAt(
      name: "Timelock",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.Timelock>;
    getContractAt(
      name: "Treasury",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.Treasury>;
    getContractAt(
      name: "ICoreVoting",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.ICoreVoting>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IERC20Permit",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "ILockingVault",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.ILockingVault>;
    getContractAt(
      name: "IVotingVault",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.IVotingVault>;
    getContractAt(
      name: "Authorizable",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.Authorizable>;
    getContractAt(
      name: "ERC20Permit",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.ERC20Permit>;
    getContractAt(
      name: "ERC20PermitWithMint",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.ERC20PermitWithMint>;
    getContractAt(
      name: "AbstractMerkleRewards",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.AbstractMerkleRewards>;
    getContractAt(
      name: "MerkleRewards",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.MerkleRewards>;
    getContractAt(
      name: "Storage",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.Storage>;
    getContractAt(
      name: "MockCoreVoting",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.MockCoreVoting>;
    getContractAt(
      name: "MockDoubleSpender",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.MockDoubleSpender>;
    getContractAt(
      name: "MockERC20",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.MockERC20>;
    getContractAt(
      name: "MockHistoryTracker",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.MockHistoryTracker>;
    getContractAt(
      name: "MockLockingVault",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.MockLockingVault>;
    getContractAt(
      name: "MockTokenLogic",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.MockTokenLogic>;
    getContractAt(
      name: "MockVotingVault",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.MockVotingVault>;
    getContractAt(
      name: "Reverter",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.Reverter>;
    getContractAt(
      name: "ReadAndWriteAnyStorage",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.ReadAndWriteAnyStorage>;
    getContractAt(
      name: "TestCoreVoting",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.TestCoreVoting>;
    getContractAt(
      name: "TestTreasury",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.TestTreasury>;
    getContractAt(
      name: "TestVestingVault",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.TestVestingVault>;
    getContractAt(
      name: "SimpleProxy",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.SimpleProxy>;
    getContractAt(
      name: "FrozenLockingVault",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.FrozenLockingVault>;
    getContractAt(
      name: "FrozenVestingVault",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.FrozenVestingVault>;
    getContractAt(
      name: "GSCVault",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.GSCVault>;
    getContractAt(
      name: "AbstractLockingVault",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.AbstractLockingVault>;
    getContractAt(
      name: "LockingVault",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.LockingVault>;
    getContractAt(
      name: "NonVotingVault",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.NonVotingVault>;
    getContractAt(
      name: "OptimisticRewards",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.OptimisticRewards>;
    getContractAt(
      name: "AbstractVestingVault",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.AbstractVestingVault>;
    getContractAt(
      name: "VestingVault",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.VestingVault>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer,
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer,
    ): Promise<ethers.Contract>;
  }
}
