/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ICoreVotingInterface extends utils.Interface {
  functions: {
    "approvedVaults(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "approvedVaults" | "approvedVaults(address)",
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "approvedVaults",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "approvedVaults(address)",
    values: [PromiseOrValue<string>],
  ): string;

  decodeFunctionResult(
    functionFragment: "approvedVaults",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvedVaults(address)",
    data: BytesLike,
  ): Result;

  events: {};
}

export interface ICoreVoting extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ICoreVotingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    approvedVaults(
      vault: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    "approvedVaults(address)"(
      vault: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;
  };

  approvedVaults(
    vault: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  "approvedVaults(address)"(
    vault: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  callStatic: {
    approvedVaults(
      vault: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    "approvedVaults(address)"(
      vault: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    approvedVaults(
      vault: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    "approvedVaults(address)"(
      vault: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    approvedVaults(
      vault: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    "approvedVaults(address)"(
      vault: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;
  };
}
