/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICoreVoting__factory } from "./ICoreVoting__factory";
export { IERC20__factory } from "./IERC20__factory";
export { IERC20Permit__factory } from "./IERC20Permit__factory";
export { ILockingVault__factory } from "./ILockingVault__factory";
export { IVotingVault__factory } from "./IVotingVault__factory";
