/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AbstractLockingVault } from "./AbstractLockingVault";
export type { LockingVault } from "./LockingVault";
