/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface GSCVaultInterface extends utils.Interface {
  functions: {
    "authorize(address)": FunctionFragment;
    "authorized(address)": FunctionFragment;
    "coreVoting()": FunctionFragment;
    "deauthorize(address)": FunctionFragment;
    "getUserVaults(address)": FunctionFragment;
    "idleDuration()": FunctionFragment;
    "isAuthorized(address)": FunctionFragment;
    "kick(address,bytes[])": FunctionFragment;
    "members(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "proveMembership(address[],bytes[])": FunctionFragment;
    "queryVotePower(address,uint256,bytes)": FunctionFragment;
    "setCoreVoting(address)": FunctionFragment;
    "setIdleDuration(uint256)": FunctionFragment;
    "setOwner(address)": FunctionFragment;
    "setVotePowerBound(uint256)": FunctionFragment;
    "votingPowerBound()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "authorize"
      | "authorize(address)"
      | "authorized"
      | "authorized(address)"
      | "coreVoting"
      | "coreVoting()"
      | "deauthorize"
      | "deauthorize(address)"
      | "getUserVaults"
      | "getUserVaults(address)"
      | "idleDuration"
      | "idleDuration()"
      | "isAuthorized"
      | "isAuthorized(address)"
      | "kick"
      | "kick(address,bytes[])"
      | "members"
      | "members(address)"
      | "owner"
      | "owner()"
      | "proveMembership"
      | "proveMembership(address[],bytes[])"
      | "queryVotePower"
      | "queryVotePower(address,uint256,bytes)"
      | "setCoreVoting"
      | "setCoreVoting(address)"
      | "setIdleDuration"
      | "setIdleDuration(uint256)"
      | "setOwner"
      | "setOwner(address)"
      | "setVotePowerBound"
      | "setVotePowerBound(uint256)"
      | "votingPowerBound"
      | "votingPowerBound()",
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "authorize",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "authorize(address)",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "authorized",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "authorized(address)",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "coreVoting",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "coreVoting()",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "deauthorize",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "deauthorize(address)",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "getUserVaults",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "getUserVaults(address)",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "idleDuration",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "idleDuration()",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorized",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorized(address)",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "kick",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>[]],
  ): string;
  encodeFunctionData(
    functionFragment: "kick(address,bytes[])",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>[]],
  ): string;
  encodeFunctionData(
    functionFragment: "members",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "members(address)",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner()", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proveMembership",
    values: [PromiseOrValue<string>[], PromiseOrValue<BytesLike>[]],
  ): string;
  encodeFunctionData(
    functionFragment: "proveMembership(address[],bytes[])",
    values: [PromiseOrValue<string>[], PromiseOrValue<BytesLike>[]],
  ): string;
  encodeFunctionData(
    functionFragment: "queryVotePower",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: "queryVotePower(address,uint256,bytes)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: "setCoreVoting",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "setCoreVoting(address)",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "setIdleDuration",
    values: [PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: "setIdleDuration(uint256)",
    values: [PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: "setOwner",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "setOwner(address)",
    values: [PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "setVotePowerBound",
    values: [PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: "setVotePowerBound(uint256)",
    values: [PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: "votingPowerBound",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "votingPowerBound()",
    values?: undefined,
  ): string;

  decodeFunctionResult(functionFragment: "authorize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorize(address)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "authorized", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorized(address)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "coreVoting", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "coreVoting()",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "deauthorize",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "deauthorize(address)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserVaults",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserVaults(address)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "idleDuration",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "idleDuration()",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorized",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorized(address)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "kick", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "kick(address,bytes[])",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "members", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "members(address)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner()", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proveMembership",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "proveMembership(address[],bytes[])",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "queryVotePower",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "queryVotePower(address,uint256,bytes)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCoreVoting",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCoreVoting(address)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIdleDuration",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIdleDuration(uint256)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setOwner(address)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVotePowerBound",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVotePowerBound(uint256)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "votingPowerBound",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "votingPowerBound()",
    data: BytesLike,
  ): Result;

  events: {
    "Kicked(address,uint256)": EventFragment;
    "MembershipProved(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Kicked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Kicked(address,uint256)"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MembershipProved"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "MembershipProved(address,uint256)",
  ): EventFragment;
}

export interface KickedEventObject {
  who: string;
  when: BigNumber;
}
export type KickedEvent = TypedEvent<[string, BigNumber], KickedEventObject>;

export type KickedEventFilter = TypedEventFilter<KickedEvent>;

export interface MembershipProvedEventObject {
  who: string;
  when: BigNumber;
}
export type MembershipProvedEvent = TypedEvent<
  [string, BigNumber],
  MembershipProvedEventObject
>;

export type MembershipProvedEventFilter =
  TypedEventFilter<MembershipProvedEvent>;

export interface GSCVault extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GSCVaultInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    authorize(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    "authorize(address)"(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    authorized(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    "authorized(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    coreVoting(overrides?: CallOverrides): Promise<[string]>;

    "coreVoting()"(overrides?: CallOverrides): Promise<[string]>;

    deauthorize(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    "deauthorize(address)"(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    getUserVaults(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[string[]]>;

    "getUserVaults(address)"(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[string[]]>;

    idleDuration(overrides?: CallOverrides): Promise<[BigNumber]>;

    "idleDuration()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    isAuthorized(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    "isAuthorized(address)"(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    kick(
      who: PromiseOrValue<string>,
      extraData: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    "kick(address,bytes[])"(
      who: PromiseOrValue<string>,
      extraData: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    members(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[BigNumber] & { joined: BigNumber }>;

    "members(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[BigNumber] & { joined: BigNumber }>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    proveMembership(
      votingVaults: PromiseOrValue<string>[],
      extraData: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    "proveMembership(address[],bytes[])"(
      votingVaults: PromiseOrValue<string>[],
      extraData: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    queryVotePower(
      who: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    "queryVotePower(address,uint256,bytes)"(
      who: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    setCoreVoting(
      _newVoting: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    "setCoreVoting(address)"(
      _newVoting: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    setIdleDuration(
      _idleDuration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    "setIdleDuration(uint256)"(
      _idleDuration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    setOwner(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    "setOwner(address)"(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    setVotePowerBound(
      _newBound: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    "setVotePowerBound(uint256)"(
      _newBound: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    votingPowerBound(overrides?: CallOverrides): Promise<[BigNumber]>;

    "votingPowerBound()"(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  authorize(
    who: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  "authorize(address)"(
    who: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  authorized(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  "authorized(address)"(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  coreVoting(overrides?: CallOverrides): Promise<string>;

  "coreVoting()"(overrides?: CallOverrides): Promise<string>;

  deauthorize(
    who: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  "deauthorize(address)"(
    who: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  getUserVaults(
    who: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<string[]>;

  "getUserVaults(address)"(
    who: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<string[]>;

  idleDuration(overrides?: CallOverrides): Promise<BigNumber>;

  "idleDuration()"(overrides?: CallOverrides): Promise<BigNumber>;

  isAuthorized(
    who: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  "isAuthorized(address)"(
    who: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  kick(
    who: PromiseOrValue<string>,
    extraData: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  "kick(address,bytes[])"(
    who: PromiseOrValue<string>,
    extraData: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  members(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  "members(address)"(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  proveMembership(
    votingVaults: PromiseOrValue<string>[],
    extraData: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  "proveMembership(address[],bytes[])"(
    votingVaults: PromiseOrValue<string>[],
    extraData: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  queryVotePower(
    who: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    arg2: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  "queryVotePower(address,uint256,bytes)"(
    who: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    arg2: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  setCoreVoting(
    _newVoting: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  "setCoreVoting(address)"(
    _newVoting: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  setIdleDuration(
    _idleDuration: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  "setIdleDuration(uint256)"(
    _idleDuration: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  setOwner(
    who: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  "setOwner(address)"(
    who: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  setVotePowerBound(
    _newBound: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  "setVotePowerBound(uint256)"(
    _newBound: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  votingPowerBound(overrides?: CallOverrides): Promise<BigNumber>;

  "votingPowerBound()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    authorize(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    "authorize(address)"(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    authorized(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    "authorized(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    coreVoting(overrides?: CallOverrides): Promise<string>;

    "coreVoting()"(overrides?: CallOverrides): Promise<string>;

    deauthorize(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    "deauthorize(address)"(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    getUserVaults(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<string[]>;

    "getUserVaults(address)"(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<string[]>;

    idleDuration(overrides?: CallOverrides): Promise<BigNumber>;

    "idleDuration()"(overrides?: CallOverrides): Promise<BigNumber>;

    isAuthorized(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    "isAuthorized(address)"(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    kick(
      who: PromiseOrValue<string>,
      extraData: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides,
    ): Promise<void>;

    "kick(address,bytes[])"(
      who: PromiseOrValue<string>,
      extraData: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides,
    ): Promise<void>;

    members(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    "members(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    proveMembership(
      votingVaults: PromiseOrValue<string>[],
      extraData: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides,
    ): Promise<void>;

    "proveMembership(address[],bytes[])"(
      votingVaults: PromiseOrValue<string>[],
      extraData: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides,
    ): Promise<void>;

    queryVotePower(
      who: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    "queryVotePower(address,uint256,bytes)"(
      who: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    setCoreVoting(
      _newVoting: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    "setCoreVoting(address)"(
      _newVoting: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    setIdleDuration(
      _idleDuration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    "setIdleDuration(uint256)"(
      _idleDuration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    setOwner(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    "setOwner(address)"(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    setVotePowerBound(
      _newBound: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    "setVotePowerBound(uint256)"(
      _newBound: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    votingPowerBound(overrides?: CallOverrides): Promise<BigNumber>;

    "votingPowerBound()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "Kicked(address,uint256)"(
      who?: PromiseOrValue<string> | null,
      when?: null,
    ): KickedEventFilter;
    Kicked(who?: PromiseOrValue<string> | null, when?: null): KickedEventFilter;

    "MembershipProved(address,uint256)"(
      who?: PromiseOrValue<string> | null,
      when?: null,
    ): MembershipProvedEventFilter;
    MembershipProved(
      who?: PromiseOrValue<string> | null,
      when?: null,
    ): MembershipProvedEventFilter;
  };

  estimateGas: {
    authorize(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    "authorize(address)"(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    authorized(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    "authorized(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    coreVoting(overrides?: CallOverrides): Promise<BigNumber>;

    "coreVoting()"(overrides?: CallOverrides): Promise<BigNumber>;

    deauthorize(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    "deauthorize(address)"(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    getUserVaults(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    "getUserVaults(address)"(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    idleDuration(overrides?: CallOverrides): Promise<BigNumber>;

    "idleDuration()"(overrides?: CallOverrides): Promise<BigNumber>;

    isAuthorized(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    "isAuthorized(address)"(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    kick(
      who: PromiseOrValue<string>,
      extraData: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    "kick(address,bytes[])"(
      who: PromiseOrValue<string>,
      extraData: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    members(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    "members(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    proveMembership(
      votingVaults: PromiseOrValue<string>[],
      extraData: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    "proveMembership(address[],bytes[])"(
      votingVaults: PromiseOrValue<string>[],
      extraData: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    queryVotePower(
      who: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    "queryVotePower(address,uint256,bytes)"(
      who: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    setCoreVoting(
      _newVoting: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    "setCoreVoting(address)"(
      _newVoting: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    setIdleDuration(
      _idleDuration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    "setIdleDuration(uint256)"(
      _idleDuration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    setOwner(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    "setOwner(address)"(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    setVotePowerBound(
      _newBound: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    "setVotePowerBound(uint256)"(
      _newBound: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    votingPowerBound(overrides?: CallOverrides): Promise<BigNumber>;

    "votingPowerBound()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    authorize(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    "authorize(address)"(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    authorized(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    "authorized(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    coreVoting(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "coreVoting()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deauthorize(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    "deauthorize(address)"(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    getUserVaults(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    "getUserVaults(address)"(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    idleDuration(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "idleDuration()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isAuthorized(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    "isAuthorized(address)"(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    kick(
      who: PromiseOrValue<string>,
      extraData: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    "kick(address,bytes[])"(
      who: PromiseOrValue<string>,
      extraData: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    members(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    "members(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proveMembership(
      votingVaults: PromiseOrValue<string>[],
      extraData: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    "proveMembership(address[],bytes[])"(
      votingVaults: PromiseOrValue<string>[],
      extraData: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    queryVotePower(
      who: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    "queryVotePower(address,uint256,bytes)"(
      who: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    setCoreVoting(
      _newVoting: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    "setCoreVoting(address)"(
      _newVoting: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    setIdleDuration(
      _idleDuration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    "setIdleDuration(uint256)"(
      _idleDuration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    setOwner(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    "setOwner(address)"(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    setVotePowerBound(
      _newBound: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    "setVotePowerBound(uint256)"(
      _newBound: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    votingPowerBound(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "votingPowerBound()"(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;
  };
}
