/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lockingVaultSol from "./LockingVault.sol";
export type { lockingVaultSol };
import type * as nonvotingVaultSol from "./NonvotingVault.sol";
export type { nonvotingVaultSol };
import type * as vestingVaultSol from "./VestingVault.sol";
export type { vestingVaultSol };
export type { FrozenLockingVault } from "./FrozenLockingVault";
export type { FrozenVestingVault } from "./FrozenVestingVault";
export type { GSCVault } from "./GSCVault";
export type { OptimisticRewards } from "./OptimisticRewards";
