name: Deploy Landing Page to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "apps/landing-page/**"
      - ".github/workflows/gh-pages-landing.yml"

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.upload-artifact.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build Landing Page
        run: yarn workspace landing-page build
        env:
          VITE_BASE_PATH: "/${{ github.event.repository.name }}/"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: apps/landing-page/dist/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
